languageCode = "en"
languageName = "English"
weight = 1
title = "Sploit Tony"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "/img/sploittony.jpg"
description = "Anthony Tuff about me."

[author]
name = "Anthony Tuff"
image = "/img/sploittony.jpg"
links = [  { email = "inert.fingers-0m@icloud.com" }, { facebook = "https://www.facebook.com/#" }, { github = "https://github.com/antonytuff" },{ instagram = "https://www.instagram.com/#" }, { linkedin = "https://www.linkedin.com//anthony-mabi-9bb18b174/" } ]
