[[main]]
none = "none"

[[main]]
name = "home"
url = "/"
weight = 5

[[main]]
name = "now"
pageRef = "now"
url = "/now/now.md"
weight = 10

[[main]]
name = "posts"
pageRef = "posts"
weight = 20

[[main]]
name = "about"
pageRef = "about"
url = "/about/about.md"
weight = 30

# [[main]]
# name = "resume"
# url = "https://www.linkedin.com/in/anthony-mabi-9bb18b174/"
# weight = 100

[[main]]
identifier = "email"
pre = "email"
url = "inert.fingers-0m@icloud.com"
weight = 110


[[main]]
identifier = "linkedin"
pre = "linkedin"
url = "https://www.linkedin.com/in/anthony-mabi-9bb18b174//"
weight = 400


[[footer]]
none = "none"
